modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/wagyourtail/jsmacros"
license = "MPL-2.0"

[[mods]]
modId = "modid"
version = "${version}"
displayName = "Example Mod"
authors = "Me!"
description = '''
    This is an example description! Tell everyone what your mod is about!
'''

[[dependencies.modid]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1]"
ordering="NONE"
side="BOTH"